app: MyApp.app

# For Xcode 4.3 and later
template: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Instruments/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate'

# For Xcode 4.2 uncomment the following line and comment out the previous one
#template: '/Developer/Platforms/iPhoneOS.platform/Developer/Library/Instruments/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate'

devices:
  My iDevice: 
    UDID  : lolffb28d74a6fraj2156090784avasc50725dd0
    screen: retina_ios5


servers:
  backend:
    host: 192.168.1.2
    port: 8080
